name: agendador-tarefas

services:
  usuario:
    build: .
    ports:
      - "8080:8080"

    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_usuario
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_usuario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  bff-agendador-tarefas:
    build: ../agendador-tarefas-bff
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8083:8083"
    depends_on:
      - usuario

  agendador-tarefas:
    build: ../agendador-tarefas
    ports:
      - "8081:8081"

    environment:
      TZ: America/Sao_Paulo
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/db_agendador
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: db_agendador
    ports:
      - "27017:27017"

  notificacao:
    build: ../notificacao
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8082:8082"